# Generated by Django 4.2 on 2023-05-04 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_alter_news_options_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
