# Generated by Django 4.2 on 2023-09-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('height', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='answers.profession')),
            ],
            options={
                'verbose_name': 'Human',
                'verbose_name_plural': 'Humans',
            },
        ),
    ]
