# Generated by Django 4.2 on 2023-09-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
