# Generated by Django 4.2 on 2023-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_human_alter_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='date_of_birth',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='human',
            name='height',
            field=models.IntegerField(max_length=3),
        ),
    ]
