# Generated by Django 4.2 on 2023-05-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_remove_human_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='height',
            field=models.IntegerField(null=True),
        ),
    ]
