# Generated by Django 4.2 on 2023-05-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_human_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='date_of_birth',
        ),
    ]
